### ISSUE TITLE
5.1.4 v-longpress 添加监听器问题

### ISSUE THREAD

**Issue by JoyMoch** [godbasin/vue-ebook#8]
阿猪，在 代码最后添加事件 监听器的时候 
`document.body.addEventListener("mousedown", el.startEvent, true);`
是不是改成
`el.addEventListener("mousedown", el.startEvent, true);`
更好一些。这样就不会在body的非绑定元素区域长按也触发指令绑定元素的事件啦(‾◡◝)

**Comment by godbasin** [comment]
很棒的建议～
